### ISSUE TITLE
GAME_MODE pvp error

### ISSUE THREAD

**Issue by thefrcrazy** [jsknnr/soulmask-dedicated-server#6]
When I start my container I automatically get the error (below) however the game mode is well defined

pve or pvp: show this Error
ERROR: GAME_MODE must be either 'pve' or 'pvp'

![CleanShot 2024-06-03 at 20 23 27](https://github.com/jsknnr/soulmask-dedicated-server/assets/37953895/ad9dbad4-911a-4c60-b6b5-2b6dae574a85)

**Comment by jsknnr** [comment]
Which version of the image are you running? Are you launching with Docker Compose?

**Comment by thefrcrazy** [comment]
Image version: latest
yeah i using docker compose command

**Comment by jsknnr** [comment]
Latest may not actually be latest. In the first entry of the log, it should list what version the image is. Also can you share your compose file without passwords.

**Comment by thefrcrazy** [comment]
My env file
```env
SERVER_NAME=Entre Couilles
GAME_MODE=pvp
SERVER_PASSWORD=serverpassword
ADMIN_PASSWORD=adminpassword
GAME_PORT=27014
QUERY_PORT=27015
SERVER_SLOTS=10
LISTEN_ADDRESS=0.0.0.0
```

My docker yml
```yml
version: '3.4'

services:
  soulmask:
    deploy:
      resources:
        limits:
          memory: 4G
          #cpus: '0.25'
    container_name: "soulmask-potes"
    image: sknnr/soulmask-dedicated-server:latest
    restart: always
    ports:
      - "27014:27014/udp"
      - "27015:27015/udp"
    env_file:
      - default.env
    volumes:
      - /home/maxim/soulmask-server/potes:/opt/soulmask
    stop_grace_period: 90s
```
