### ISSUE TITLE
Did`t start server

### ISSUE THREAD

**Issue by Fuzik762** [jsknnr/soulmask-dedicated-server#8]
Hello, i tried start server with docker compose / docker, but server killed on row:

> [2024.06.11-18.05.42:375][  0]logSqliteHelper: (FDBRecordDeclare::Execute)CREATE TABLE: CREATE TABLE IF NOT EXISTS `actor_table` (`actor_serial` INTEGER PRIMARY KEY AUTOINCREMENT, `server_id` INTEGER NOT NULL, `data_version` INTEGER NOT NULL, `actor_name` TEXT, `actor_level` TEXT, `actor_script` TEXT NOT NULL, `actor_owner` TEXT, `actor_transf` TEXT, `actor_data` BLOB, `actor_time` TEXT);
Killed
[2024.06.11-18.05.42:375][  0]logSqliteHelper: (FDBRecordDeclare::Execute)CREATE INDEX: CREATE INDEX IF NOT EXISTS idx_acto
2024-06-11 18:08:13,993 INFO: Shutdown complete. Goodbye, Chieftan.

What am I doing wrong?

**Comment by jsknnr** [comment]
The log entry above the shutdown is just the SQL migrations to get the database ready, those are normal. The Shutdown complete entry means that the soulmask pid exited. I would need to see more logs, there is not enough here.

- Provide more logs
- Provide commands used to start with docker and docker compose
- Provide container host OS information
- Provide information on file system used for mounting persistent volume into container

**Comment by Fuzik762** [comment]
Sure 
[_soulmask-server-fuzik_logs2.txt](https://github.com/user-attachments/files/15805506/_soulmask-server-fuzik_logs2.txt) - killed on server basic info

[_soulmask-server-fuzik_logs.txt](https://github.com/user-attachments/files/15805507/_soulmask-server-fuzik_logs.txt) - killed on sql

Start commands are taken from the repo
Docker:
```bash 
docker run \
  --detach \
  --name soulmask-server-fuzik \
  --mount type=volume,source=soulmask-persistent-data,target=/home/steam/soulmask \
  --publish 27050:27050/udp \
  --publish 27051:27051/udp \
  --env=SERVER_NAME='Soulmask Containerized Server' \
  --env=GAME_MODE='pve' \
  --env=SERVER_SLOTS=3 \
  --env=SERVER_PASSWORD='99998888' \
  --env=ADMIN_PASSWORD='123456789' \
  --env=GAME_PORT=27050 \
  --env=QUERY_PORT=27051 \
  --env=LISTEN_ADDRESS='0.0.0.0' \
  --stop-timeout 90 \
  sknnr/soulmask-dedicated-server:latest
  ```
Docker-compose:
```yaml
services:
  soulmask:
    image: sknnr/soulmask-dedicated-server:latest
    ports:
      - "27050:27050/udp"
      - "27051:27051/udp"
    env_file:
      - default.env
    volumes:
      - soulmask-persistent-data:/home/steam/soulmask
    stop_grace_period: 90s

volumes:
  soulmask-persistent-data:
```
  Host: 
  OS: CentOS 7
  CPU: 2x2000MHz
  RAM: 4GB
  
Volume: 
information from portainer: 
```
Destination /home/steam/soulmask
Driver local
Mode z
Name soulmask-persistent-data
Propagation
RW true
Source /var/lib/docker/volumes/soulmask-persistent-data/_data
Type volume
```
information from terminal:
```
drwx-----x 3 10000 10000        4096 Jun 11 20:52  soulmask-persistent-data
```
